const breweriesByState = {
  "Alabama": [],
  "Alaska": [],
  "Arizona": [],
  "Arkansas": [],
  "California": [],
  "Colorado": [],
  "Connecticut": [],
  "Delaware": [],
  "Florida": [],
  "Georgia": [],
  "Hawaii": [],
  "Idaho": [],
  "Illinois": [],
  "Indiana": [],
  "Iowa": [],
  "Kansas": [],
  "Kentucky": [],
  "Louisiana": [],
  "Maine": [],
  "Maryland": [],
  "Massachusetts": [],
  "Michigan": [],
  "Minnesota": [],
  "Mississippi": [],
  "Missouri": [],
  "Montana": [],
  "Nebraska": [],
  "Nevada": [],
  "New Hampshire": [],
  "New Jersey": [],
  "New Mexico": [],
  "New York": [],
  "North Carolina": [],
  "North Dakota": [],
  "Ohio": [],
  "Oklahoma": [],
  "Oregon": [],
  "Pennsylvania": [],
  "Rhode Island": [],
  "South Carolina": [],
  "South Dakota": [],
  "Tennessee": [],
  "Texas": ["Cactus Land Brewing Co.","Dr. Jeckyll's Beer Lab"],
  "Utah": [],
  "Vermont": [],
  "Virginia": ["Chef Life Brewery","Rockfish Brewing Company"],
  "Washington": ["Bardic Brewing and Cider - Spokane","Bardic Brewing and Cider - Spokane Valley"],
  "West Virginia": [],
  "Wisconsin": ["Duesterbeck's Brewing Company","Fifth Ward Brewing Company","Lakefront Brewery","Herbiery Brewing","Stubborn Brothers Brewery","Stillmank Brewing Co."],
  "Wyoming": []
};
