const breweriesByState = {
  "Alabama": ["Goat Island Brewing","Iron Hand Brewing, LLC"],
  "Alaska": ["Southern Tail Brewing"],
  "Arizona": ["Button Brew House"],
  "Arkansas": ["Southern Tail Brewing"],
  "California": ["All Points Brewing Co.","AudioGraph Beer Co.","Lincoln Beer Company","Porchlight Brewing Company","TapRoom Beer Co.","The Keg Stand Brewing Co."],
  "Colorado": [],
  "Connecticut": ["Grimm Brothers"],
  "Delaware": [],
  "Florida": [],
  "Georgia": [],
  "Hawaii": [],
  "Idaho": [],
  "Illinois": [],
  "Indiana": [],
  "Iowa": [],
  "Kansas": [],
  "Kentucky": [],
  "Louisiana": [],
  "Maine": [],
  "Maryland": [],
  "Massachusetts": [],
  "Michigan": [],
  "Minnesota": [],
  "Mississippi": [],
  "Missouri": [],
  "Montana": [],
  "Nebraska": [],
  "Nevada": [],
  "New Hampshire": [],
  "New Jersey": [],
  "New Mexico": [],
  "New York": ["Apex Brewery","Catskill Brewery","Gardiner Brewing Company"],
  "North Carolina": [],
  "North Dakota": [],
  "Ohio": ["Combustion Brewery & Taproom - Clintonville","Combustion Brewery & Taproom - Pickerington"],
  "Oklahoma": ["Stonecloud Brewing"],
  "Oregon": [],
  "Pennsylvania": ["Rock God Brewing Co.","Rural City Beer Company","ShawneeCraft Brewing Company","Vault Brewing Co - Easton","Vault Brewing Co - Yardley","Vortex Brewing Company","Whiskers Brewing Inc"],
  "Rhode Island": ["Apponaug Brewing Company"],
  "South Carolina": [],
  "South Dakota": [],
  "Tennessee": ["Cedar Glade Brews","Soul & Spirits Brewery","Twisted Copper Brewing Company - Columbia","Twisted Copper Brewing Company - Mt. Pleasant"],
  "Texas": ["Bankhead Brewpub - Farmers Branch","Bankhead Brewpub - Rowlett","Cactus Land Brewing Co.","Celestial Beerworks","Dr. Jeckyll's Beer Lab","Forney Brewing Company","Highway 71 Brewing"],
  "Utah": [],
  "Vermont": [],
  "Virginia": ["Chef Life Brewery","Rockfish Brewing Company"],
  "Washington": ["Bardic Brewing and Cider - Spokane","Bardic Brewing and Cider - Spokane Valley"],
  "West Virginia": [],
  "Wisconsin": ["Duesterbeck's Brewing Company","Fifth Ward Brewing Company","Lakefront Brewery","Herbiery Brewing","Stubborn Brothers Brewery","Stillmank Brewing Co."],
  "Wyoming": []
};
