// breweries-data.js
// Static data source for user-facing brewery list

window.BREWERIES_BY_STATE = {
  Alabama: [],
  Alaska: [],
  Arizona: [],
  Arkansas: [],
  California: [],
  Colorado: [
    "Example Brewing Co",
    "Mountain Ale Works",
    "High Plains Brewery"
  ],
  Connecticut: [],
  Delaware: [],
  Florida: [],
  Georgia: [],
  Hawaii: [],
  Idaho: [],
  Illinois: [],
  Indiana: [],
  Iowa: [],
  Kansas: [],
  Kentucky: [],
  Louisiana: [],
  Maine: [],
  Maryland: [],
  Massachusetts: [],
  Michigan: [],
  Minnesota: [],
  Mississippi: [],
  Missouri: [],
  Montana: [],
  Nebraska: [],
  Nevada: [],
  New Hampshire: [],
  New Jersey: [],
  New Mexico: [],
  New York: [],
  North Carolina: [],
  North Dakota: [],
  Ohio: [],
  Oklahoma: [],
  Oregon: [],
  Pennsylvania: [],
  Rhode Island: [],
  South Carolina: [],
  South Dakota: [],
  Tennessee: [],
  Texas: [],
  Utah: [],
  Vermont: [],
  Virginia: [],
  Washington: [],
  West Virginia: [],
  Wisconsin: [],
  Wyoming: []
};

